packages:
  - '.'

allowBuilds:
  msgpackr-extract: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@expo/cli@56.1.19'
  - '@expo/config-plugins@56.0.12'
  - '@expo/fingerprint@0.19.7'
  - '@expo/prebuild-config@56.0.19'
  - '@expo/router-server@56.0.16'
  - babel-preset-expo@56.0.17
  - expo-asset@56.0.19
  - expo-modules-autolinking@56.0.19
  - expo-modules-core@56.0.20
  - expo-modules-jsi@56.0.12
  - expo@56.0.15
  - '@expo/ui@56.0.21'
  - expo-app-metrics@56.0.21
  - expo-image-picker@56.0.20
  - expo-insights@56.0.20
  - expo-notifications@56.0.20
  - expo-observe@56.0.24
  - expo-router@56.2.14
  - expo-sharing@56.0.21

overrides:
  uuid: ^11.1.1
  form-data: ^4.0.6
  js-yaml: ^4.2.0
