import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../../constants/Config';
export const materialsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContainer: {
    paddingHorizontal: 16,
    paddingVertical: 20,
  },
  headerInfo: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F1EA',
    marginBottom: 20,
  },
  subtitle: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontFamily: FONTS.mono,
  },
  sheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#ECE7DD',
    borderWidth: 1,
    borderRadius: 18,
    padding: 16,
    marginBottom: 15,
  },
  siIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FAF1DC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  siBody: {
    flex: 1,
    marginLeft: 14,
  },
  siName: {
    fontSize: 15.5,
    fontFamily: FONTS.displaySemiBold,
    color: COLORS.textPrimary,
  },
  siDesc: {
    fontSize: 12.5,
    fontFamily: FONTS.body,
    color: COLORS.textSecondary,
    marginTop: 4,
    lineHeight: 16,
  },
  siChevron: {
    paddingLeft: 8,
  },
  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F1EA',
    backgroundColor: '#fff',
  },
  backButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: '#F4F1EA',
    borderRadius: 8,
  },
  backButtonText: {
    fontSize: 12,
    fontFamily: FONTS.bodyMedium,
    color: COLORS.textSecondary,
  },
  subHeaderTitle: {
    fontSize: 16,
    fontFamily: FONTS.displaySemiBold,
    color: COLORS.textPrimary,
    marginLeft: 15,
  },
  quoteCard: {
    backgroundColor: '#fff',
    borderColor: '#ECE7DD',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  quoteText: {
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textPrimary,
    fontFamily: FONTS.bodyMedium,
    fontStyle: 'italic',
  },
  quoteMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F4F1EA',
    paddingTop: 8,
  },
  quoteSource: {
    fontSize: 11,
    fontFamily: FONTS.mono,
    color: COLORS.amber,
  },
  quoteTime: {
    fontSize: 11,
    fontFamily: FONTS.mono,
    color: COLORS.textMuted,
  },
  playerCard: {
    backgroundColor: '#FCFAF5',
    borderColor: '#ECE7DD',
    borderWidth: 1,
    borderRadius: 20,
    padding: 20,
    marginBottom: 25,
    alignItems: 'center',
  },
  playerTitle: {
    fontSize: 17,
    fontFamily: FONTS.displaySemiBold,
    color: COLORS.textPrimary,
  },
  playerSubtitle: {
    fontSize: 12,
    fontFamily: FONTS.body,
    color: COLORS.textSecondary,
    marginTop: 4,
  },
  progressLineBg: {
    height: 4,
    width: '100%',
    backgroundColor: '#E7E3DA',
    borderRadius: 2,
    marginTop: 20,
  },
  progressLine: {
    height: '100%',
    backgroundColor: COLORS.amber,
    borderRadius: 2,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 8,
  },
  timeText: {
    fontSize: 10.5,
    fontFamily: FONTS.mono,
    color: COLORS.textMuted,
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  controlBtn: {
    padding: 10,
    marginHorizontal: 15,
  },
  controlText: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  playBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.amber,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playText: {
    color: '#fff',
    fontSize: 16,
    marginLeft: 3,
  },
  playlistTitle: {
    fontSize: 12,
    fontFamily: FONTS.monoMedium,
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  audioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#F4F1EA',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  audioNum: {
    width: 24,
    fontSize: 11,
    fontFamily: FONTS.mono,
    color: COLORS.textMuted,
  },
  audioName: {
    flex: 1,
    fontSize: 14,
    fontFamily: FONTS.bodyMedium,
    color: COLORS.textPrimary,
  },
  audioDuration: {
    fontSize: 11,
    fontFamily: FONTS.mono,
    color: COLORS.textMuted,
  },
});
