import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../../constants/Config';
export const navigatorStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContainer: {
    paddingHorizontal: 16,
    paddingBottom: 40,
  },
  headerInfo: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F1EA',
    marginBottom: 20,
  },
  subtitle: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontFamily: FONTS.mono,
  },
  pillButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAF1DC',
    borderColor: '#F0DFB8',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 15,
  },
  pillButtonText: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 12,
    color: COLORS.amber,
  },
  node: {
    flexDirection: 'row',
    marginBottom: 0,
    minHeight: 80,
  },
  nodeFuture: {
    opacity: 0.5,
  },
  rail: {
    width: 32,
    alignItems: 'center',
  },
  dot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#ECE7DD',
    borderWidth: 1.5,
    borderColor: '#A69D8F',
  },
  dotDone: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#B9770C',
    borderColor: '#B9770C',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkMark: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  dotActive: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#E0951A',
    borderColor: '#FAF1DC',
    borderWidth: 3,
  },
  line: {
    width: 2,
    flex: 1,
    backgroundColor: '#ECE7DD',
  },
  lineDone: {
    backgroundColor: '#B9770C',
  },
  lineFaint: {
    backgroundColor: '#ECE7DD',
  },
  nodeBody: {
    flex: 1,
    paddingLeft: 16,
    paddingBottom: 25,
  },
  nodeStep: {
    fontSize: 11,
    fontFamily: FONTS.monoMedium,
    color: COLORS.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  nodeTitle: {
    fontSize: 15,
    color: COLORS.textPrimary,
    fontFamily: FONTS.displaySemiBold,
    marginTop: 2,
  },
  nodeTitleActive: {
    fontSize: 16,
  },
  activeCard: {
    backgroundColor: '#FCFAF5',
    borderColor: '#ECE7DD',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginTop: 12,
  },
  cardText: {
    fontSize: 13,
    lineHeight: 18,
    color: COLORS.textSecondary,
    fontFamily: FONTS.body,
  },
  mergeNote: {
    fontSize: 11,
    fontFamily: FONTS.monoMedium,
    color: COLORS.amber,
    marginTop: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  materialsList: {
    marginTop: 10,
  },
  materialLink: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#F4F1EA',
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
  },
  materialIcon: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FCFAF5',
    borderRadius: 6,
  },
  materialBody: {
    flex: 1,
    marginLeft: 10,
  },
  materialKind: {
    fontSize: 9,
    fontFamily: FONTS.monoMedium,
    color: COLORS.textMuted,
    textTransform: 'uppercase',
  },
  materialTitle: {
    fontSize: 13,
    fontFamily: FONTS.bodyMedium,
    color: COLORS.textPrimary,
    marginTop: 1,
  },
  materialCheck: {
    color: COLORS.amber,
    fontWeight: 'bold',
    fontSize: 14,
    marginRight: 4,
  },
  materialCircle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: COLORS.amber,
    marginRight: 4,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(34, 30, 23, 0.4)',
  },
  backdropPress: {
    flex: 1,
  },
  bottomSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 34 : 20,
    maxHeight: '80%',
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E7E3DA',
    alignSelf: 'center',
    marginBottom: 15,
  },
  sheetHeader: {
    paddingHorizontal: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F1EA',
  },
  sheetTitle: {
    fontSize: 18,
    fontFamily: FONTS.displaySemiBold,
    color: COLORS.textPrimary,
  },
  sheetSub: {
    fontSize: 11,
    fontFamily: FONTS.mono,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  sheetBody: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F4F1EA',
  },
  secItemDone: {
    opacity: 0.6,
  },
  secNum: {
    width: 24,
    fontSize: 11,
    fontFamily: FONTS.monoMedium,
    color: COLORS.textMuted,
  },
  secNumDone: {
    color: COLORS.textMuted,
  },
  secName: {
    flex: 1,
    fontSize: 14,
    fontFamily: FONTS.body,
    color: COLORS.textPrimary,
  },
  secNameDone: {
    color: COLORS.textSecondary,
    textDecorationLine: 'line-through',
  },
  secNameActive: {
    fontFamily: FONTS.bodyMedium,
    color: COLORS.amber,
  },
  secState: {
    width: 24,
    alignItems: 'flex-end',
  },
  secCheck: {
    color: COLORS.amber,
    fontWeight: 'bold',
    fontSize: 12,
  },
  secDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.amber,
  },
  secCircle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#ECE7DD',
  },
});
