import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../constants/Config';

export const chatListStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.background },
  headerContainer: { backgroundColor: COLORS.background },
  summaryContainer: {
    flexDirection: 'row', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingTop: 16, paddingBottom: 14,
    borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  statChip: {
    flex: 1, backgroundColor: COLORS.bgSurface,
    borderWidth: 1, borderColor: COLORS.borderSoft,
    borderRadius: 14, padding: 10, marginHorizontal: 4, minHeight: 80, justifyContent: 'center',
  },
  statNum: { fontSize: 22, color: COLORS.textPrimary, fontFamily: FONTS.displaySemiBold, marginBottom: 4 },
  amberText: { color: COLORS.amber },
  statLabel: { fontSize: 10, lineHeight: 12, color: COLORS.textSecondary, fontFamily: FONTS.body },
  banner: {
    backgroundColor: COLORS.amberTint, borderRadius: 14,
    marginHorizontal: 20, marginTop: 16, padding: 16,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    borderWidth: 1, borderColor: COLORS.border,
  },
  bannerTextContainer: { flex: 1 },
  bannerEyebrow: { fontSize: 9, letterSpacing: 1, textTransform: 'uppercase', color: COLORS.amber, fontFamily: FONTS.mono },
  bannerTitle: { fontSize: 15, color: COLORS.textPrimary, fontFamily: FONTS.displaySemiBold, marginTop: 3 },
  bannerButton: { backgroundColor: COLORS.amber, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 8 },
  bannerButtonText: { color: '#ffffff', fontSize: 12, fontFamily: FONTS.bodySemiBold },
  gtabsContainer: { marginTop: 16, borderBottomWidth: 1, borderBottomColor: COLORS.border },
  gtabsScroll: { paddingHorizontal: 16, paddingBottom: 2 },
  gtab: { paddingHorizontal: 16, paddingVertical: 12, marginRight: 4, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  gtabActive: { borderBottomColor: COLORS.amber },
  gtabText: { fontSize: 14.5, color: COLORS.textSecondary, fontFamily: FONTS.body },
  gtabTextActive: { color: COLORS.textPrimary, fontFamily: FONTS.bodySemiBold },
  chatRow: {
    flexDirection: 'row', paddingVertical: 14, paddingHorizontal: 20,
    borderBottomWidth: 1, borderBottomColor: COLORS.borderSoft, alignItems: 'center',
  },
  avatar: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: COLORS.bgSurface, borderWidth: 1, borderColor: COLORS.borderStrong,
    justifyContent: 'center', alignItems: 'center', marginRight: 14,
  },
  avatarWarrior: { borderColor: COLORS.amber, backgroundColor: COLORS.amberGlow },
  avatarText: { color: COLORS.textSecondary, fontSize: 16, fontFamily: FONTS.bodyMedium },
  avatarTextWarrior: { color: COLORS.amber, fontFamily: FONTS.bodySemiBold },
  chatBody: { flex: 1, marginRight: 8 },
  chatTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 },
  chatName: { fontSize: 15.5, color: COLORS.textSecondary, fontFamily: FONTS.bodyMedium },
  chatNameUnread: { color: COLORS.textPrimary, fontFamily: FONTS.bodySemiBold },
  chatTime: { fontSize: 11, color: COLORS.textMuted, fontFamily: FONTS.mono },
  chatPreview: { fontSize: 13, lineHeight: 18, color: COLORS.textMuted, fontFamily: FONTS.body },
  chatPreviewUnread: { color: COLORS.textSecondary, fontFamily: FONTS.bodyMedium },
  previewAuthor: { color: COLORS.textSecondary, fontFamily: FONTS.bodyMedium },
  practiceContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  practiceDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: COLORS.amberBright, marginRight: 6 },
  practiceText: { fontSize: 11, color: COLORS.amberSoft, fontFamily: FONTS.body },
  badgeContainer: {
    minWidth: 18, height: 18, borderRadius: 9,
    backgroundColor: COLORS.textMuted, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4,
  },
  badgeAmber: { backgroundColor: COLORS.amber },
  badgeText: { color: '#ffffff', fontSize: 10, fontFamily: FONTS.monoMedium },
  emptyText: { textAlign: 'center', marginTop: 50, color: COLORS.textMuted, fontFamily: FONTS.body, fontSize: 14 },
  errorText: { color: COLORS.warn, fontSize: 16, marginBottom: 15, textAlign: 'center', fontFamily: FONTS.body },
  retryButton: { backgroundColor: COLORS.amber, paddingHorizontal: 20, paddingVertical: 10, borderRadius: 10 },
  retryButtonText: { color: '#fff', fontSize: 15, fontFamily: FONTS.bodySemiBold },
});
