import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../constants/Config';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
  },
  profileCard: {
    backgroundColor: COLORS.bgSurface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#282114',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#DCD5C7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  avatarWarrior: {
    borderColor: COLORS.amber,
    backgroundColor: COLORS.amberGlow,
  },
  avatarText: {
    fontFamily: FONTS.bodySemiBold,
    fontSize: 22,
    color: '#5F5848',
  },
  avatarTextWarrior: {
    color: COLORS.amber,
  },
  profileDetails: {
    flex: 1,
  },
  profileName: {
    fontFamily: FONTS.displaySemiBold,
    fontSize: 18,
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  profileEmail: {
    fontFamily: FONTS.mono,
    fontSize: 12,
    color: COLORS.textSecondary,
    marginBottom: 6,
  },
  roleText: {
    fontFamily: FONTS.bodySemiBold,
    fontSize: 13,
    color: COLORS.amberSoft,
    marginTop: 2,
  },
  sectionTitle: {
    fontFamily: FONTS.monoMedium,
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: COLORS.textSecondary,
    marginBottom: 10,
    paddingLeft: 4,
  },
  menuGroup: {
    backgroundColor: COLORS.bgSurface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    overflow: 'hidden',
    marginBottom: 24,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderSoft,
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemText: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 14,
    color: COLORS.textPrimary,
    marginLeft: 12,
  },
  menuItemTextDanger: {
    fontFamily: FONTS.bodySemiBold,
    fontSize: 14,
    color: COLORS.warn,
    marginLeft: 12,
  },
  versionContainer: {
    alignItems: 'center',
    marginTop: 10,
  },
  versionText: {
    fontFamily: FONTS.mono,
    fontSize: 11,
    color: COLORS.textMuted,
  },
  // Таймер практики
  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingVertical: 4,
  },
  backButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: COLORS.bgSurface,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    marginRight: 16,
  },
  backButtonText: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 14,
    color: COLORS.amber,
  },
  subHeaderTitle: {
    fontFamily: FONTS.displaySemiBold,
    fontSize: 20,
    color: COLORS.textPrimary,
  },
  timerDisplay: {
    backgroundColor: COLORS.bgSurface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    shadowColor: '#282114',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 2,
  },
  timerDigits: {
    fontFamily: FONTS.monoMedium,
    fontSize: 64,
    color: COLORS.textPrimary,
    letterSpacing: 2,
  },
  timerLabel: {
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 8,
  },
  chipsTitle: {
    fontFamily: FONTS.monoMedium,
    fontSize: 11,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: COLORS.textSecondary,
    marginBottom: 12,
    paddingLeft: 4,
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 24,
  },
  chip: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: COLORS.bgSurface,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
  },
  chipActive: {
    backgroundColor: COLORS.amberTint,
    borderColor: COLORS.amber,
  },
  chipText: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  chipTextActive: {
    color: COLORS.amber,
    fontFamily: FONTS.bodySemiBold,
  },
  soundContainer: {
    backgroundColor: COLORS.bgSurface,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.borderSoft,
    padding: 16,
    marginBottom: 32,
  },
  soundOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderSoft,
  },
  soundOptionLast: {
    borderBottomWidth: 0,
  },
  soundRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.8,
    borderColor: COLORS.borderStrong,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  soundRadioActive: {
    borderColor: COLORS.amber,
  },
  soundRadioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.amber,
  },
  soundOptionText: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  soundOptionTextActive: {
    fontFamily: FONTS.bodySemiBold,
    color: COLORS.textPrimary,
  },
  controlsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  btnControl: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  btnStart: {
    backgroundColor: COLORS.amber,
    borderColor: COLORS.amber,
  },
  btnPause: {
    backgroundColor: COLORS.bgSurface,
    borderColor: COLORS.borderStrong,
  },
  btnReset: {
    backgroundColor: COLORS.bgSurface,
    borderColor: COLORS.borderSoft,
  },
  btnTextStart: {
    fontFamily: FONTS.bodySemiBold,
    fontSize: 15,
    color: '#FFFFFF',
  },
  btnTextPause: {
    fontFamily: FONTS.bodySemiBold,
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  btnTextReset: {
    fontFamily: FONTS.bodyMedium,
    fontSize: 15,
    color: COLORS.textSecondary,
  },
});
