import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../constants/Config';

export const usersStyles = StyleSheet.create({
  keyboardAvoidingView: { flex: 1 },
  container: { flex: 1, backgroundColor: COLORS.background },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.background },
  listContainer: { paddingVertical: 10 },
  userItem: {
    flexDirection: 'row', paddingHorizontal: 20, paddingVertical: 14,
    borderBottomWidth: 1, borderBottomColor: '#F4F1EA', alignItems: 'center',
  },
  avatar: {
    width: 44, height: 44, borderRadius: 22,
    backgroundColor: '#FAF8F5', borderWidth: 1, borderColor: '#ECE7DD',
    justifyContent: 'center', alignItems: 'center', marginRight: 15,
  },
  avatarWarrior: { borderColor: COLORS.amber, backgroundColor: COLORS.amberGlow },
  avatarText: { fontSize: 16, color: COLORS.textSecondary, fontFamily: FONTS.bodySemiBold },
  avatarTextWarrior: { color: COLORS.amber },
  userInfo: { flex: 1 },
  nameRow: { flexDirection: 'row', alignItems: 'center' },
  userName: { fontSize: 15, color: COLORS.textPrimary, marginRight: 8, fontFamily: FONTS.displaySemiBold },
  userEmail: { fontSize: 12.5, color: COLORS.textSecondary, fontFamily: FONTS.mono, marginTop: 2 },
  emptyText: { textAlign: 'center', marginTop: 50, color: COLORS.textMuted, fontFamily: FONTS.body },
  roleBadge: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 9, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  studentBadge: { backgroundColor: '#F4F1EA', borderColor: '#ECE7DD' },
  warriorBadge: { backgroundColor: '#FCF4E3', borderColor: '#F0DFB8' },
  roleBadgeText: { fontSize: 9, fontFamily: FONTS.monoMedium, letterSpacing: 0.5, textTransform: 'uppercase' },
  studentBadgeText: { color: COLORS.textSecondary },
  warriorBadgeText: { color: COLORS.amber },
  fab: {
    position: 'absolute', right: 20, bottom: 20,
    backgroundColor: COLORS.amber, width: 56, height: 56, borderRadius: 28,
    justifyContent: 'center', alignItems: 'center',
    shadowColor: '#282114', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 6, elevation: 4,
  },
  fabIcon: { color: '#fff', fontSize: 28, fontWeight: '500', lineHeight: 30 },
  modalOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(34, 30, 23, 0.42)' },
  modalCard: {
    backgroundColor: '#fff', borderRadius: 24, padding: 24, width: '90%', maxWidth: 400,
    shadowColor: '#282114', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.15, shadowRadius: 20, elevation: 8,
  },
  modalTitle: { fontSize: 20, marginBottom: 20, textAlign: 'center', color: COLORS.textPrimary, fontFamily: FONTS.displaySemiBold },
  input: {
    borderWidth: 1, borderColor: '#ECE7DD', backgroundColor: '#FCFAF5',
    borderRadius: 14, paddingHorizontal: 14, paddingVertical: 10, marginBottom: 15,
    fontSize: 14, color: COLORS.textPrimary, fontFamily: FONTS.body,
  },
  roleLabel: { fontSize: 11, fontFamily: FONTS.monoMedium, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 8, color: COLORS.textSecondary },
  roleContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 25 },
  roleChip: { flex: 1, paddingVertical: 8, marginHorizontal: 3, borderRadius: 8, borderWidth: 1, borderColor: 'transparent', alignItems: 'center', backgroundColor: '#F4F1EA' },
  activeRoleChip: { borderColor: '#F0DFB8', backgroundColor: '#FAF1DC' },
  roleChipText: { fontSize: 10.5, color: COLORS.textSecondary, fontFamily: FONTS.bodyMedium },
  activeRoleChipText: { color: COLORS.amber, fontFamily: FONTS.bodySemiBold },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-between' },
  modalButton: { flex: 1, paddingVertical: 14, borderRadius: 14, alignItems: 'center', marginHorizontal: 5 },
  cancelButton: { backgroundColor: '#F4F1EA' },
  createButton: { backgroundColor: COLORS.amber },
  cancelButtonText: { color: COLORS.textSecondary, fontSize: 15, fontFamily: FONTS.bodySemiBold },
  createButtonText: { color: '#fff', fontSize: 15, fontFamily: FONTS.bodySemiBold },
});
